-----
# Data Cleaning
-----

To clean the email data by addressing null and duplicated values.

## Set Up
---

In [25]:
import numpy as np
import pandas as pd

## Functions
-----

In [26]:
def df_check (df):

    shape = df.shape
    nulls = df.isna().sum().sum()
    duplicated_rows = df.duplicated().sum()
    duplicated_cols = df.columns.duplicated().sum()


    print (f"""      
    Number of Rows: {shape[0]}     
    Number of Columns: {shape[1]}     
    Number of Nulls: {nulls}       
    Number of Duplicated Rows: {duplicated_rows}
    Number of Duplicated Cols: {duplicated_cols}
        """)

## Data Loading

In [27]:
emails_df  = pd.read_csv('../../data/processed_emails.csv', index_col=0)

In [28]:
emails_df.head()

,from,to,subject,body
0,phillip.allen@enron.com,tim.belden@enron.com,NaN,Here is our forecast
1,phillip.allen@enron.com,john.lavorato@enron.com,Re:,Traveling to have a business meeting takes the...
2,phillip.allen@enron.com,leah.arsdall@enron.com,Re: test,test successful. way to go!!!
3,phillip.allen@enron.com,randall.gay@enron.com,NaN,"Randy,\n\n Can you send me a schedule of the s..."
4,phillip.allen@enron.com,greg.piper@enron.com,Re: Hello,Let's shoot for Tuesday at 11:45.

In [29]:
df_check(emails_df)

    Number of Rows: 517401
    Number of Columns: 4
    Number of Nulls: 28333
    Number of Duplicated Rows: 264855
    Number of Duplicated Cols: 0

In [32]:
cleaned_df = emails_df.copy()

### Nulls
----

In [30]:
emails_df.isna().sum()

from           0
to          9146
subject    19187
body           0
dtype: int64

#### 1. Null Recipients

In [31]:
emails_df[emails_df['to'].isna()]

,from,to,subject,body
1230,outlook-migration-team@enron.com,NaN,Lee Odonnel,loan servicing-jessica weeber 800-393-5626 jwe...
1231,outlook-migration-team@enron.com,NaN,Greg Thorse,exit mccollough off 410
3909,jeff.youngflesh@enron.com,NaN,Lexmark Document/Workflow mgmt intro,Lexmark Solution Services intro to GSS BD. Ga...
4395,john.arnold@enron.com,NaN,NaN,"To ""Outstanding"" Analysts and Associates:\nI ..."
4442,ann.schmidt@enron.com,NaN,Enron Mentions,Dabhol lenders to vote today on PPA PPPPA term...
...,...,...,...,...
516316,john.phillips@clarionenergy.com,NaN,Corrected Post-AGA NYMEX straddles,Sent wrong file previously-- We apologize
516731,andy.zipper@enron.com,NaN,"EDS Arcordia, set up meeting Kolodgie",Spoke with Kolodgie. Arcordia is run out of Lo...
516732,andy.zipper@enron.com,NaN,Red Meteor etc.,TASK ASSIGNMENT\n\n\nTask Priority:\t\t\nTask ...
516846,john.zufferli@enron.com,NaN,NaN,Conference call with UBS
516976,janet.mulero@ubsw.com,NaN,Re: Market Risk Meeting Today - John Zufferli,Hi.\n\n The Market Risk Meeting has been s...

-----
**Comment:**

After looking into the null recipients, cases where the to are missing either they are addressed to email groups or no recipient can be found. Making the decision to remove all cases where recipients are missing, for this project I think it important to work with a complete dataset for more accurate insights, models and results.

In [33]:
cleaned_df.dropna(subset=['to'], inplace=True)

In [35]:
cleaned_df.reset_index(drop=True, inplace=True)

#### 2. Null Subject

In [36]:
emails_df[emails_df['subject'].isna()]

,from,to,subject,body
0,phillip.allen@enron.com,tim.belden@enron.com,NaN,Here is our forecast
3,phillip.allen@enron.com,randall.gay@enron.com,NaN,"Randy,\n\n Can you send me a schedule of the s..."
6,phillip.allen@enron.com,"david.l.johnson@enron.com, john.shafer@enron.com",NaN,Please cc the following distribution list with...
11,phillip.allen@enron.com,stagecoachmama@hotmail.com,NaN,"Lucy,\n\n Here are the rentrolls:\n\n\n\n Open..."
14,phillip.allen@enron.com,david.delainey@enron.com,NaN,"Dave, \n\n Here are the names of the west desk..."
...,...,...,...,...
516846,john.zufferli@enron.com,NaN,NaN,Conference call with UBS
516853,frank.hayden@enron.com,john.zufferli@enron.com,NaN,Sorry I missed call. My understanding is that...
517247,john.zufferli@enron.com,majordomo@majordomo.pjm,NaN,unsubscribe pjm-customer-info
517289,john.zufferli@enron.com,john.lavorato@enron.com,NaN,home number is (403) 685-4817
517311,john.zufferli@enron.com,john.postlethwaite@enron.com,NaN,"Please give Enpower access to Murray Fichten, ..."

------
**Comment:** 

Making decision to also drop cases where email subject is missing from the dataset. Emails with missing subjects only make up 3% of the dataset and for me its more imporant to have a complete dataset for this project and 3% data loss is not a big sacrifice to me.

In [37]:
cleaned_df.dropna(subset=['subject'], inplace=True)

In [38]:
cleaned_df.reset_index(drop=True, inplace=True)

#### ReCheck of Nulls

In [39]:
df_check(cleaned_df)

    Number of Rows: 489243
    Number of Columns: 4
    Number of Nulls: 0
    Number of Duplicated Rows: 251032
    Number of Duplicated Cols: 0

### Duplicated Emails
-----

In [40]:
cleaned_df[cleaned_df.duplicated()]

,from,to,subject,body
414,phillip.allen@enron.com,keith.holst@enron.com,Consolidated positions: Issues & To Do list,---------------------- Forwarded by Phillip K ...
415,phillip.allen@enron.com,keith.holst@enron.com,Consolidated positions: Issues & To Do list,---------------------- Forwarded by Phillip K ...
416,phillip.allen@enron.com,paula.harris@enron.com,Re: 2001 Margin Plan,"Paula,\n\n 35 million is fine\n\nPhillip"
417,phillip.allen@enron.com,ina.rangel@enron.com,"Var, Reporting and Resources Meeting",---------------------- Forwarded by Phillip K ...
418,phillip.allen@enron.com,pallen70@hotmail.com,Westgate,---------------------- Forwarded by Phillip K ...
...,...,...,...,...
489144,john.zufferli@enron.com,cooper.richey@enron.com,FW: Ontario overview,"-----Original Message-----\nFrom: \tTripp, Gar..."
489164,john.zufferli@enron.com,daniel.diamond@enron.com,RE: Canadian Online Counterparties,Here is the list updated with responsibility n...
489181,john.zufferli@enron.com,chris.dorland@enron.com,FW: 1996 Porsche 993 C4S,"i lifted it last night for 82,000\n -----Origi..."
489199,john.zufferli@enron.com,chris.dorland@enron.com,1998 Silver C4S,Check out www.segalmotorcar.com
489230,john.zufferli@enron.com,louise.kitchen@enron.com,FW: Strictly Confidential,Here is the info for the commercial staff\n\nJ...

----
**Comment:**

Making the decision to drop all duplicated emails.

In [42]:
cleaned_df.drop_duplicates(inplace=True)

In [43]:
cleaned_df.reset_index(drop= True, inplace=True)

In [44]:
cleaned_df

,from,to,subject,body
0,phillip.allen@enron.com,john.lavorato@enron.com,Re:,Traveling to have a business meeting takes the...
1,phillip.allen@enron.com,leah.arsdall@enron.com,Re: test,test successful. way to go!!!
2,phillip.allen@enron.com,greg.piper@enron.com,Re: Hello,Let's shoot for Tuesday at 11:45.
3,phillip.allen@enron.com,greg.piper@enron.com,Re: Hello,"Greg,\n\n How about either next Tuesday or Thu..."
4,phillip.allen@enron.com,joyce.teixeira@enron.com,Re: PRC review - phone calls,any morning between 10 and 11:30
...,...,...,...,...
238206,john.zufferli@enron.com,kori.loibl@enron.com,Trade with John Lavorato,This is a trade with OIL-SPEC-HEDGE-NG (John L...
238207,john.zufferli@enron.com,john.lavorato@enron.com,Gas Hedges,Some of my position is with the Alberta Term b...
238208,john.zufferli@enron.com,dawn.doucet@enron.com,RE: CONFIDENTIAL,2\n\n -----Original Message-----\nFrom: \tDouc...
238209,john.zufferli@enron.com,jeanie.slone@enron.com,Calgary Analyst/Associate,Analyst\t\t\t\t\tRank\n\nStephane Brodeur\t\t\...
238210,john.zufferli@enron.com,livia_zufferli@monitor.com,RE: ali's essays,i think the YMCA has a class that is for peopl...

#### ReCheck of Duplicates

In [45]:
df_check(cleaned_df)

    Number of Rows: 238211
    Number of Columns: 4
    Number of Nulls: 0
    Number of Duplicated Rows: 0
    Number of Duplicated Cols: 0

## Summary
----

With the email data now cleaned, I can progress to some eda and clustering to gather some insights into the dataset.